[ARC]
RBF=JTRASTAN
MOD=0
NAME=RBISLAND
DEFAULT=0xBFFE0000
CONF="P1,Switches"
CONF="P1OG,Cabinet,Upright,Cocktail"
CONF="P1OH,Flip Screen,On,Off"
CONF="P1OI,Service Mode,On,Off"
CONF="P1OJ,Demo Sounds,Off,On"
CONF="P1OKL,Coin A,2/3,2/1,1/2,1/1"
CONF="P1OMN,Coin B,1/6,1/4,1/3,1/2"
CONF="P1OOP,Difficulty,Hardest,Hard,Easy,Medium"
CONF="P1OQ,1PUP,None,100k 1000k"
CONF="P1OR,Complete Bonus,100k,1 Up"
CONF="P1OST,Lives,2,1,4,3"
CONF="P1OU,Language,English,Japanese"
CONF="P1OV,Coin Mode,Mode B,Mode A"
BUTTONS="Rainbow,Jump,Start,Coin,Core credits"
