[ARC]
RBF=JTCPS1
MOD=5
NAME=1941
DEFAULT=0x9FFCFF0000
CONF="P1,Switches"
CONF="P1OOQ,Difficulty,7,6,5,4,3,2,1,0"
CONF="P1OTU,Bullet's Speed,Very Fast,Fast,Slow,Very Slow"
CONF="P1OV,Initial Vitality,4 Bars,3 Bars"
CONF="P1OW,Throttle Game Speed,Off,On"
CONF="P1OY,Free Play,On,Off"
CONF="P1OZ,Freeze,On,Off"
CONF="P1Oa,Flip Screen,On,Off"
CONF="P1Ob,Demo Sounds,On,Off"
CONF="P1Oc,Allow Continue,Yes,No"
CONF="P1Od,Game Mode,Test,Game"
CONF="P1Ok,Service Mode,On,Off"
CONF="P1Oe,PCB type,88617A,89626A"
BUTTONS="Shoot,Bomb,-,-,-,-,Start,Coin,Core credits"
