[ARC]
RBF=JTCPS1
MOD=0
NAME=SF2ACCP2
DEFAULT=0x9FFCFF0000
CONF="P1,Switches"
CONF="P1OOQ,Difficulty,7,6,5,4,3,2,1,0"
CONF="P1ORT,Game speed,Slowest,Speed test mode,Very slow,Slow,Normal,Fast,Very fast,Extremely fast"
CONF="P1OU,Guile rapid shots,On,Off"
CONF="P1OV,Blanka rapid shots,On,Off"
CONF="P1OW,Ken rapid shots,On,Off"
CONF="P1OX,Ryu rapid shots,On,Off"
CONF="P1OY,Free Play,On,Off"
CONF="P1OZ,Freeze,On,Off"
CONF="P1Oa,Flip Screen,On,Off"
CONF="P1Ob,Demo Sounds,On,Off"
CONF="P1Oc,Allow Continue,Yes,No"
CONF="P1Od,Game Mode,Test,Game"
CONF="P1Oe,PCB type,88617A,89626A"
BUTTONS="LP,MP,SP,LK,MK,HK,Start,Coin,Core credits"
